### ISSUE TITLE
Check for circular imports and enforce import order

### ISSUE THREAD

**Issue by ba-talibe** [wikit-ai/olaf#25]
After using the [cProfile](https://docs.python.org/3.10/library/profile.html) built-in Python package, it turns out that most of the import time might come from circular imports, forcing some locking and unlocking processes. We should check for those and enforce import orders.

**Comment by schmarion** [comment]
Vérifier les imports circulaires dans le framework. 

Par exemple dans `olaf>pipeline>pipeline_component>pipeline_component_schema.py` dans la méthode `run`, l'attribut `pipeline` est de type `Any` car si on le met de type `Pipeline` le code plante à cause de imports circulaires.
