### ISSUE TITLE
Create non llm default pipeline

### ISSUE THREAD

**Issue by ba-talibe** [wikit-ai/olaf#94]

**Comment by schmarion** [comment]
Création d'une pipeline sans composant LLM dans un script de démonstration. 
Par exemple : 
- Extraction de termes pour les concepts avec le POS tagging sur les noms
- Regroupement en concepts avec l'agglomerative clustering
- Extraction de termes pour les relations avec le POS tagging sur les verbes
- Regroupement en relations avec l'agglomerative clustering
- Serialisation avec OWLAxiomExtraction

Il faudrait pouvoir lancer cette pipeline avec une commance comme `olaf run pipeline <nom_du_fichier>`
